### PR TITLE
Add UML Diagram for External Intfs

### LINKED ISSUE #22: Replace external interfaces table with UML diagram
### Purpose

Make this information easier to understand.

### Prerequisites
- [ ] Add support for UML rendering in sailbot workspace

### Resources

- https://github.com/UBCSailbot/custom_interfaces?tab=readme-ov-file#project-wide-external-interfaces
- https://www.lucidchart.com/blog/types-of-UML-diagrams
- Could also consider Mermaid
    - https://www.dandoescode.com/blog/plantuml-vs-mermaid
    - https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/creating-diagrams#creating-mermaid-diagrams

### PR DESCRIPTION
**Pull request by hhenry01**
### Description

- Resolves #22 
- Blocked by https://github.com/UBCSailbot/sailbot_workspace/pull/212 and #28 
- Also removed Local Transceiver as one of the subscribers for `filtered_wind_sensors` because I think it's an unnecessary extra amount of data we'd need to transmit over satellite (more $$$)
- I think uploading the rendered diagram to github and rendering it in the README is helpful.

### Verification

- Renders as:
image

### Resources

- https://plantuml.com/state-diagram

### CODE REVIEW

**Comment by hhenry01** [comment]
There's currently some confusion over the status of the global_path topic using a msg or a service, so I'm waiting on that to resolve before continuing.

**Comment by hhenry01** [comment]
I'm guessing the other interface tables are simple enough to understand without a diagram. Alternatively we could make one of the members do the other diagrams.

**Review by patrick-5546 — APPROVED** [review]
LGTM, will also want to verify that this renders correctly on docs site once merged in

**Comment by hhenry01** [comment]
It does not render on the docs site.

**Pull request merged**
