### PR TITLE
Fix HelperROT.msg

### PR DESCRIPTION
**Pull request by hhenry01**
### Description

- HelperROT.msg had the wrong units datatype.

### Verification

- Description of ROT https://documentation.spire.com/ais-fundamentals/rate-of-turn-rot/ from the original PR https://github.com/UBCSailbot/custom_interfaces/pull/13

### Resources

-

### CODE REVIEW

**Comment by hhenry01** [comment]
@SPDonaghy fyi

**Comment by SPDonaghy** [comment]
Just saw this, thanks Henry!

**Comment by jamenkaye** [comment]
Interesting, nice catch Henry! Looks good to me. I assume this is specific to the AIS device we're using right?

**Comment by hhenry01** [comment]
> Interesting, nice catch Henry! Looks good to me. I assume this is specific to the AIS device we're using right?

This is part of the  AIS standard: https://www.navcen.uscg.gov/ais-class-a-reports

**Review by ubcsailbotsoftware — APPROVED** [review]

**Pull request merged**
